apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "topology.kubernetes.io/zone" # If not included, all zones are considered
      operator: In
      values: ["$AWS_REGIONa", "$AWS_REGIONb", "$AWS_REGIONc"]
    - key: "kubernetes.io/arch" # If not included, all architectures are considered
      operator: In
      values: ["amd64"]
    - key: "kubernetes.io/os" # If not included, all operating systems are considered
      operator: In
      values: ["linux"]
    - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["spot", "on-demand"]
  limits:
    resources:
      cpu: 1000      
  provider:
    instanceProfile: "KarpenterNodeInstanceProfile-$CLUSTER_NAME
  ttlSecondsAfterEmpty: 30

