apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: custom-kube-scheduler-test
  labels:
    app: alpine
  annotations:
    UseCustomKubeScheduler: 'true'
    CustomPodScheduleStrategy: 'nodesize=od4vcpu16gb,base=1,weight=0:nodesize=spot4vcpu16gb,weight=1:nodesize=spot8vcpu32gb,weight=1'
    #CustomPodScheduleStrategy: 'lifecycle=spot&30ase=1,weight=0:lifecycle=od,80weight=1:nodesize=spot8vcpu32gb,weight=1'
spec:
  replicas: 10
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - name: alpine
          image: alpine
          imagePullPolicy: IfNotPresent
          args:
          - sleep
          - infinity
          - 2>&1
