apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
- name: sidecar-injector.morven.me
  clientConfig:
    service:
      name: sidecar-injector-webhook-svc
      namespace: sidecar-injector
      path: "/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01UQXdOREEzTkRjd04xb1hEVE13TVRBd01qQTNORGN3TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2xvCm5oSWtsWVp2RU1EREVkMjUxNmlobjh1WXovd1B6T1kzTUR6Q1hJQ0pQM3pFUTIyTHVpWlR1RXN2NU8zQVM4dFMKUDVLN1B0RmRqV1doQTlWZnBaUVBnMTJnZmFVWW1XckpRZVFLQm85OUlaZTFzZkMvdW1DMnd3V0tqdkFDU09wSwpmNS8wcktYa0ZKdG8wWnBiL0JOQWhWaS8xOHdoWE44N0dpQ25HaVNoSmJqYkdSbFhjcVlmRFRNUzZzSFNEWEIrCkpLNFBtdDdna3MxQzVncnpBVHRmcUlzck43QlRJVEM0c2dnOGozSVQ4RC9reG0vdU1vNzQwUzc5cElTcHp6QmkKSGJVb085QXgzYXRoYitFdFhXbzF1dkg2c2lkSUU4WWF2bzZDbm1jZW93V29FTFlZZEhKSUdBSFJ0OEl3Y1NRTgpBQjdLNjFpTjhHTnBpOUhWU2pjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHVVZ5YTdneDhoT2ZyTGJOanMwendhbzF1KzgKQzJ6cHRCV1lzaGxvZnBVNFhsWTlYSDYzazIzUjI4alo1L0QweE1yL0RjWU12dzlFNnE1aC9LQUlBMFNrNE96TwpLeEV6WHprN1IzSDN6STAyalZ2OGh3MVk0bFZzVVp4M242QnNVek0rNnBuQ1JKc1c3NTVkQ3BvMHlKOW9pdnp6CjlmOCtwYjN1OU1xWnp4NE5INWx4cUpmbS9xTTNpclBBcHBFeHR3QWY4RVNiZjU3MzR6QXJyZ2pFV1ArOHJuVzEKZWcwcmpnMHVKWlJkbkJXRFdRUDFXcUFMZDhVMGEydDllbGhNVlJXQlUrN005ZGlKWldiclNBanRBUGwxOUVUQQpQeHYvcmN5UDJWYldaR1o4QjlUQlRGb0llVEU4UkN0RUpFWnNVRm9zVmYzQll0S2lTRXFMOTdvc01sbz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      sidecar-injection: enabled
