apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: custom-kube-scheduler-webhook
  labels:
    app: custom-kube-scheduler-webhook
webhooks:
- name: custom-kube-scheduler-webhook
  clientConfig:
    service:
      name: custom-kube-scheduler-webhook
      namespace: custom-kube-scheduler-webhook
      path: "/mutate"
    caBundle: ${CA_BUNDLE}
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      sidecar-injection: enabled
